POST  http://localhost:3000/api/user/register
Content-Type: application/json

{
"name": "another user",
"email":"anotheremail1@gmail.com",
"password":"12345678"
}

###

POST  http://localhost:3000/api/user/login
Content-Type: application/json

{
"email":"anotheremail1@gmail.com",
"password":"12345678"
}

###
GET http://localhost:4000/api/posts
# add bearer token to Authorization
# Authorization: Bearer tokengoeshere

###
GET http://localhost:4000/api/posts/userinfo
# Authorization: Bearer tokengoeshere

###
POST  http://localhost:3000/api/posts/create
Content-Type: application/json
# Authorization: Bearer tokengoeshere

{
"title": "My first post",
"message": "login posts"
}