POST  http://localhost:3000/api/user/register
Content-Type: application/json

{
"name": "another user",
"email":"anotheremail@gmail.com",
"password":"12345678"
}

###

POST  http://localhost:3000/api/user/login
Content-Type: application/json

{
"email":"anotheremail@gmail.com",
"password":"12345678"
}

###
GET http://localhost:4000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTVjNjY2MjdmMjAzZTc2ZjU5NWE0YWQiLCJpYXQiOjE2MzM0NDc4ODEsImV4cCI6MTYzMzQ0NzkwMH0.oXQ2XRx0swxit050waTI87JH6X3bzEuxd7sIf9c1o2c

###
GET http://localhost:4000/api/posts/userinfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTVjNjY2MjdmMjAzZTc2ZjU5NWE0YWQiLCJpYXQiOjE2MzM0NDc4ODEsImV4cCI6MTYzMzQ0NzkwMH0.oXQ2XRx0swxit050waTI87JH6X3bzEuxd7sIf9c1o2c
