POST  http://localhost:3000/api/user/register
Content-Type: application/json

{
"name": "another user",
"email":"anotheremail1@gmail.com",
"password":"12345678"
}

###

POST  http://localhost:3000/api/user/login
Content-Type: application/json

{
"email":"anotheremail1@gmail.com",
"password":"12345678"
}

###
GET http://localhost:4000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTVjODAwNDc5OTgyNDk2ZjA2ZjcxNWIiLCJpYXQiOjE2MzM0NTk0NTYsImV4cCI6MTYzMzQ1OTQ3NX0._8t8CLjt3R7OhIcpjTehOiqSOD6D7m3C01sQ19ZwYD8

###
GET http://localhost:4000/api/posts/userinfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTVjODAwNDc5OTgyNDk2ZjA2ZjcxNWIiLCJpYXQiOjE2MzM0NTQ0MjQsImV4cCI6MTYzMzQ1NDQ1NH0.10wTHVJXN1boMXUJoaTC9HXzEx_3O6bUHArMOPDOrcA

###
POST  http://localhost:3000/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTVjODAwNDc5OTgyNDk2ZjA2ZjcxNWIiLCJpYXQiOjE2MzM0NTk0MjMsImV4cCI6MTYzMzQ1OTQ0Mn0.0JVOw9FQkCXBbNRCzypdXCZtL07jdOgG_DRhWaqyjKo

{
"title": "My first post",
"message": "login posts"
}